name: Update Afternoon Tasks to Evening in Notion

on:
  schedule:
    - cron: "30 12 * * *" # 6:00 PM IST (12:30 PM UTC)
  workflow_dispatch: # allows manual run

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Run updateAfternoonToEvening script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_TODOS_DATABASE_ID: ${{ secrets.NOTION_TODOS_DATABASE_ID }}
        # run: node to-dos_db/updateAfternoonToEvening
        run: npm run todos:evening
